## http://www.pinkmuff.com/ config
_config = {
 "_maxPage": 4000,
 "_memcachedServer": ["127.0.0.1:11211"],
 "_memcachedEnabled": True,
 "_memcachedPagesTimeout": 86400,
 "_memcachedVideosTimeout": 86400,
 "_memcachedPrefix": "##MEMCACHED_PREFIX##",
 "_mongoServer": {"host": "127.0.0.1", "port": 27017},
 "_esIndex": "pornlinks",
 "_mongoDb": {"name": "porn", "links": "links"},
 "_mongoOffset": 0,
 "_numVidsTiled": 60,
 "_appLogFileName": "logs/app/app.log",
 "_site_title": "##FQDN##",
 "_site_css": "main",
 "_staticHost": "static.##FQDN##",
 "_standaloneIP": "0.0.0.0",
 "_standalonePort": 65080,
 "_debug": 0,
 "_error404": ("Location","/"),
 "_twitter": "",
 "_email": "",
 "_btc_donate": "14rXeD3SFeopjvuHi7kU4gbnbewM6k1iE7",
 "_mobile_ua": ["iPhone","iPad","Mobile Safari","Android","DoCoMo","SAMSUNG-SGH","Windows Phone"],
 "search_placeholder": "Anal",
 "cache_expires": "21600",
 "base_template": "base.tpl",
 "video_template": "video.tpl",
 "about_template": "about.tpl",
 "main_page_ad": '',
 "video_page_ad": '',
 "footer_popunder": '',
 "marquee": '<marquee style="position: fixed; width: 0px;"><a href="http://www.pinkmuff.com/">www.pinkmuff.com</a></marquee>',
 "META_KEYWORDS": "",
 "META_DESCRIPTION": "",
 "MS_VALIDATE": "",
 "GOOGLE_SITE_VERIFICATION": "",
 "YANDEX_VERIFICATION": "",
 "_byline": "",
 "_ga_code": "",
 "_ga_site": "",
}

_friends = {
  "Pink Muff": "http://www.pinkmuff.com/",
  "Digital Ocean Hosting": "https://www.linode.com/?r=d841da92f44278f5afe5f2bf910b3be87c33a8c1"
}

_categories = {
  "anal": ["tags", "anal", "Anal", '##ANAL SPECIFIC POPUNDER##'],
  "milf": ["tags", "milf", "MILF", '##MILF SPECIFIC POPUNDER##'],
  "teen": ["tags", "teen", "Teen"],
  "gay":  ["tags", "gay", "Gay"],
  "asian": ["tags", "asian", "Asian"],
  "blowjob": ["tags", "blowjob", "Blowjob"],
  "black": ["tags", "black", "Black"],
  "redhead": ["tags", "redhead", "Redhead"],
  "orgy": ["tags", "orgy", "Orgy"],
  "gangbang": ["tags", "gangbang", "Gangbang"],
  "brunette": ["tags", "brunette", "Brunette"],
  "blonde": ["tags", "blonde", "Blonde"],
  "bbw": ["tags", "bbw", "BBW"],
  "lesbians": ["tags", "lesbian", "Lesbian"],
  "bondage": ["tags", "bondage", "Bondage"],
  "amateur": ["tags", "amateur", "Amateur"],
  "homemade": ["tags", "homemade", "Homemade"],
  "pov": ["tags", "pov", "POV"],
  "group": ["tags", "group", "Group"],
  "gangbang": ["tags", "gangbang", "Gangbang"],
  "anime": ["tags", "anime", "Anime"],
  "tattoo": ["tags", "tattoo", "Tattoo"],
}

